spring.application.name=blogApp

spring.datasource.url=jdbc:postgresql://localhost:5432/blogdb
spring.datasource.username=postgres
spring.datasource.password=Admin@8810

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=QnJ2QUY1d1l2ZEhKZ2RjZ1VobGd5V1p1WW5qSHdYd1lZbE1qclR4S1lqbnJZb1ZMS3I0Z3R2ekU=



logging.level.org.springframework=DEBUG
logging.level.com.mahdi.blogApp=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE